import PptxGenJS from 'pptxgenjs';
import type { AnalysisResult } from '@/types/types';

export interface BriefingIncidentMeta {
  id: string;
  title: string;
  severity: string;
  status: string;
  service: string;
  opened_at: string;
  time_window: string;
}

const P = {
  bg: '0a0e14',
  panel: '151a21',
  border: '1f2937',
  amber: 'f59e0b',
  red: 'dc2626',
  orange: 'f97316',
  teal: '14b8a6',
  blue: '3b82f6',
  white: 'ffffff',
  gray1: '94a3b8',
  gray2: '475569',
  gray3: '1e293b',
} as const;

const SEV_COLOR: Record<string, string> = {
  CRITICAL: P.red,
  HIGH: P.orange,
  MEDIUM: P.amber,
  LOW: P.teal,
};

function confColor(c: number): string {
  if (c >= 0.8) return P.red;
  if (c >= 0.65) return P.orange;
  if (c >= 0.45) return P.amber;
  return P.teal;
}

function truncate(s: string, n: number): string {
  if (!s) return '';
  return s.length > n ? `${s.slice(0, n - 1)}…` : s;
}

function formatTs(iso: string): string {
  try {
    return new Date(iso).toLocaleString('en-US', {
      month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit', hour12: false,
    });
  } catch {
    return iso;
  }
}

function formatWindow(tw: string): string {
  return tw.replace('last_', 'Last ').replace('m', ' min').replace('h', ' hr');
}

type BriefingAnalysis = AnalysisResult & { aiBrief?: Record<string, string> };

/** Build a 6-slide executive briefing PPTX entirely in the browser. */
export async function generateIncidentBriefingPptx(
  analysis: BriefingAnalysis,
  incident: BriefingIncidentMeta,
): Promise<void> {
  const pres = new PptxGenJS();
  pres.layout = 'LAYOUT_16x9';
  pres.title = `Incident Briefing ${incident.id}`;
  pres.author = 'SentinelOps';

  const sevColor = SEV_COLOR[incident.severity.toUpperCase()] ?? P.amber;
  const briefSummary = analysis.aiBrief?.executiveSummary ?? analysis.summary ?? '';
  const technicalFindings = analysis.aiBrief?.technicalFindings ?? '';
  const immediateRisk = analysis.aiBrief?.immediateRisk ?? '';
  const genDate = formatTs(analysis.generatedAt ?? new Date().toISOString());
  const hypotheses = (analysis.hypotheses ?? []).slice(0, 3);
  const timeline = (analysis.timeline ?? []).slice(0, 7);
  const actions = (analysis.recommendedActions ?? [])
    .map((a) => (typeof a === 'string' ? a : String(a)))
    .slice(0, 6);
  const br = analysis.blastRadius ?? { services: [], endpoints: [] };

  // ── Slide 1: Cover ──────────────────────────────────────────────────────────
  {
    const s = pres.addSlide();
    s.background = { color: P.bg };
    s.addShape(pres.ShapeType.rect, { x: 0, y: 0, w: 0.22, h: 5.625, fill: { color: sevColor } });
    s.addShape(pres.ShapeType.rect, { x: 0.22, y: 0, w: 9.78, h: 0.55, fill: { color: P.panel }, line: { color: P.border, width: 1 } });
    s.addText('SentinelOps', { x: 0.4, y: 0, w: 4, h: 0.55, fontSize: 13, bold: true, color: P.amber, fontFace: 'Arial', valign: 'middle' });
    s.addText('AGENTIC INCIDENT COMMANDER', { x: 4.4, y: 0, w: 5.4, h: 0.55, fontSize: 9, color: P.gray1, fontFace: 'Arial', align: 'right', valign: 'middle', charSpacing: 3 });
    s.addShape(pres.ShapeType.rect, { x: 0.5, y: 0.85, w: 2.0, h: 0.42, fill: { color: sevColor }, rectRadius: 0.05 });
    s.addText(incident.id, { x: 0.5, y: 0.85, w: 2.0, h: 0.42, fontSize: 14, bold: true, color: P.white, fontFace: 'Arial', align: 'center', valign: 'middle' });
    s.addShape(pres.ShapeType.rect, { x: 2.65, y: 0.85, w: 1.6, h: 0.42, fill: { color: sevColor, transparency: 80 }, line: { color: sevColor, width: 1 }, rectRadius: 0.05 });
    s.addText(incident.severity, { x: 2.65, y: 0.85, w: 1.6, h: 0.42, fontSize: 11, bold: true, color: sevColor, fontFace: 'Arial', align: 'center', valign: 'middle', charSpacing: 2 });
    s.addText(truncate(incident.title, 80), { x: 0.5, y: 1.48, w: 8.8, h: 1.5, fontSize: 26, bold: true, color: P.white, fontFace: 'Arial', valign: 'top', autoFit: true });
    const metaItems = [
      { label: 'SERVICE', value: incident.service },
      { label: 'STATUS', value: incident.status },
      { label: 'OPENED', value: formatTs(incident.opened_at) },
      { label: 'WINDOW', value: formatWindow(incident.time_window) },
    ];
    metaItems.forEach((m, i) => {
      const bx = 0.5 + i * 2.28;
      s.addShape(pres.ShapeType.rect, { x: bx, y: 3.15, w: 2.1, h: 0.75, fill: { color: P.gray3 }, line: { color: P.border, width: 1 }, rectRadius: 0.05 });
      s.addText(m.label, { x: bx + 0.1, y: 3.21, w: 1.9, h: 0.22, fontSize: 8, color: P.gray1, fontFace: 'Arial', charSpacing: 2 });
      s.addText(m.value, { x: bx + 0.1, y: 3.45, w: 1.9, h: 0.3, fontSize: 11, bold: true, color: P.white, fontFace: 'Arial' });
    });
    s.addShape(pres.ShapeType.line, { x: 0.5, y: 4.1, w: 8.8, h: 0, line: { color: P.border, width: 1 } });
    s.addText(`Generated by SentinelOps · Confidential · ${genDate}`, { x: 0.5, y: 4.2, w: 8.8, h: 0.3, fontSize: 9, color: P.gray2, fontFace: 'Arial', align: 'center' });
    s.addText('1 / 6', { x: 9.3, y: 5.1, w: 0.6, h: 0.3, fontSize: 9, color: P.gray2, fontFace: 'Arial', align: 'right' });
  }

  // ── Slide 2: Summary ────────────────────────────────────────────────────────
  {
    const s = pres.addSlide();
    s.background = { color: P.bg };
    s.addShape(pres.ShapeType.rect, { x: 0, y: 0, w: 10, h: 0.6, fill: { color: P.panel }, line: { color: P.border, width: 1 } });
    s.addText('INCIDENT SUMMARY', { x: 0.4, y: 0, w: 6, h: 0.6, fontSize: 11, bold: true, color: P.amber, fontFace: 'Arial', valign: 'middle', charSpacing: 3 });
    s.addText(incident.id, { x: 6, y: 0, w: 3.7, h: 0.6, fontSize: 11, color: P.gray1, fontFace: 'Arial', align: 'right', valign: 'middle' });
    s.addShape(pres.ShapeType.rect, { x: 0.35, y: 0.85, w: 9.3, h: 1.55, fill: { color: P.gray3 }, line: { color: P.amber, width: 1 }, rectRadius: 0.07 });
    s.addText('Executive Summary', { x: 0.55, y: 0.92, w: 5, h: 0.28, fontSize: 9, color: P.amber, fontFace: 'Arial', bold: true, charSpacing: 2 });
    s.addText(truncate(briefSummary, 400) || 'No summary available.', { x: 0.55, y: 1.22, w: 9.0, h: 1.1, fontSize: 11, color: P.white, fontFace: 'Arial', autoFit: true });
    if (technicalFindings) {
      s.addShape(pres.ShapeType.rect, { x: 0.35, y: 2.6, w: 9.3, h: 1.45, fill: { color: P.panel }, line: { color: P.border, width: 1 }, rectRadius: 0.07 });
      s.addText('Technical Findings', { x: 0.55, y: 2.67, w: 5, h: 0.28, fontSize: 9, color: P.gray1, fontFace: 'Arial', bold: true, charSpacing: 2 });
      s.addText(truncate(technicalFindings, 350), { x: 0.55, y: 2.96, w: 9.0, h: 1.0, fontSize: 10, color: P.gray1, fontFace: 'Arial', autoFit: true });
    }
    if (immediateRisk) {
      s.addShape(pres.ShapeType.rect, { x: 0.35, y: 4.2, w: 9.3, h: 0.7, fill: { color: P.red, transparency: 85 }, line: { color: P.red, width: 1 }, rectRadius: 0.07 });
      s.addText('IMMEDIATE RISK', { x: 0.55, y: 4.28, w: 2.2, h: 0.28, fontSize: 8, color: P.red, fontFace: 'Arial', bold: true });
      s.addText(truncate(immediateRisk, 200), { x: 2.55, y: 4.28, w: 6.9, h: 0.55, fontSize: 10, color: P.white, fontFace: 'Arial', autoFit: true });
    }
    s.addText('2 / 6', { x: 9.3, y: 5.1, w: 0.6, h: 0.3, fontSize: 9, color: P.gray2, fontFace: 'Arial', align: 'right' });
  }

  // ── Slide 3: Hypotheses ───────────────────────────────────────────────────
  {
    const s = pres.addSlide();
    s.background = { color: P.bg };
    s.addShape(pres.ShapeType.rect, { x: 0, y: 0, w: 10, h: 0.6, fill: { color: P.panel }, line: { color: P.border, width: 1 } });
    s.addText('ROOT CAUSE HYPOTHESES', { x: 0.4, y: 0, w: 7, h: 0.6, fontSize: 11, bold: true, color: P.amber, fontFace: 'Arial', valign: 'middle', charSpacing: 3 });
    s.addText('Ranked by confidence score', { x: 5.5, y: 0, w: 4.2, h: 0.6, fontSize: 9, color: P.gray1, fontFace: 'Arial', align: 'right', valign: 'middle' });
    const rowH = 1.48;
    if (hypotheses.length === 0) {
      s.addText('No hypotheses generated — run Analyze first.', { x: 0.5, y: 1.2, w: 9, h: 0.5, fontSize: 12, color: P.gray1, fontFace: 'Arial' });
    }
    hypotheses.forEach((h, i) => {
      const ry = 0.75 + i * (rowH + 0.07);
      const pct = Math.round(h.confidence * 100);
      const bc = confColor(h.confidence);
      s.addShape(pres.ShapeType.rect, { x: 0.35, y: ry, w: 9.3, h: rowH, fill: { color: P.panel }, line: { color: P.border, width: 1 }, rectRadius: 0.07 });
      s.addShape(pres.ShapeType.ellipse, { x: 0.5, y: ry + 0.08, w: 0.38, h: 0.38, fill: { color: bc } });
      s.addText(String(i + 1), { x: 0.5, y: ry + 0.08, w: 0.38, h: 0.38, fontSize: 13, bold: true, color: P.white, fontFace: 'Arial', align: 'center', valign: 'middle' });
      s.addText(h.title, { x: 1.02, y: ry + 0.08, w: 6.3, h: 0.38, fontSize: 12, bold: true, color: P.white, fontFace: 'Arial' });
      s.addText(`${pct}%`, { x: 8.4, y: ry + 0.08, w: 1.1, h: 0.38, fontSize: 15, bold: true, color: bc, fontFace: 'Arial', align: 'right', valign: 'middle' });
      const barY = ry + 0.54;
      const barW = 8.5;
      s.addShape(pres.ShapeType.rect, { x: 0.55, y: barY, w: barW, h: 0.14, fill: { color: P.gray2, transparency: 70 }, rectRadius: 0.07 });
      s.addShape(pres.ShapeType.rect, { x: 0.55, y: barY, w: barW * h.confidence, h: 0.14, fill: { color: bc }, rectRadius: 0.07 });
      const ev0 = h.evidence?.[0] ? truncate(h.evidence[0], 120) : '';
      const ev1 = h.evidence?.[1] ? truncate(h.evidence[1], 120) : '';
      if (ev0) s.addText(`· ${ev0}`, { x: 0.6, y: ry + 0.76, w: 8.8, h: 0.25, fontSize: 9, color: P.gray1, fontFace: 'Arial' });
      if (ev1) s.addText(`· ${ev1}`, { x: 0.6, y: ry + 1.03, w: 8.8, h: 0.25, fontSize: 9, color: P.gray1, fontFace: 'Arial' });
    });
    s.addText('3 / 6', { x: 9.3, y: 5.1, w: 0.6, h: 0.3, fontSize: 9, color: P.gray2, fontFace: 'Arial', align: 'right' });
  }

  // ── Slide 4: Blast radius ─────────────────────────────────────────────────
  {
    const s = pres.addSlide();
    s.background = { color: P.bg };
    s.addShape(pres.ShapeType.rect, { x: 0, y: 0, w: 10, h: 0.6, fill: { color: P.panel }, line: { color: P.border, width: 1 } });
    s.addText('BLAST RADIUS', { x: 0.4, y: 0, w: 6, h: 0.6, fontSize: 11, bold: true, color: P.amber, fontFace: 'Arial', valign: 'middle', charSpacing: 3 });
    s.addText('Impact Scope Assessment', { x: 5.5, y: 0, w: 4.2, h: 0.6, fontSize: 9, color: P.gray1, fontFace: 'Arial', align: 'right', valign: 'middle' });
    const statCards = [
      { label: 'SERVICES AFFECTED', value: String(br.services?.length ?? 0), color: P.red },
      { label: 'ENDPOINTS HIT', value: String(br.endpoints?.length ?? 0), color: P.orange },
      { label: 'USERS IMPACTED', value: br.estimated_users_affected ? br.estimated_users_affected.toLocaleString() : 'N/A', color: P.amber },
      { label: 'REVENUE IMPACT', value: br.estimated_revenue_impact || 'Monitoring', color: P.gray1 },
    ];
    statCards.forEach((c, i) => {
      const cx = 0.35 + i * 2.36;
      s.addShape(pres.ShapeType.rect, { x: cx, y: 0.8, w: 2.18, h: 1.05, fill: { color: P.gray3 }, line: { color: c.color, width: 1 }, rectRadius: 0.07 });
      s.addText(c.label, { x: cx + 0.1, y: 0.88, w: 2.0, h: 0.22, fontSize: 8, color: c.color, fontFace: 'Arial', bold: true, charSpacing: 1 });
      s.addText(c.value, { x: cx + 0.1, y: 1.14, w: 2.0, h: 0.55, fontSize: 20, bold: true, color: P.white, fontFace: 'Arial' });
    });
    s.addText('AFFECTED SERVICES', { x: 0.4, y: 2.05, w: 9, h: 0.28, fontSize: 9, color: P.gray1, bold: true, charSpacing: 2, fontFace: 'Arial' });
    (br.services ?? []).slice(0, 6).forEach((svc, i) => {
      const sy = 2.44 + i * 0.38;
      s.addShape(pres.ShapeType.rect, { x: 0.4, y: sy, w: 4.25, h: 0.3, fill: { color: P.panel }, line: { color: P.border, width: 1 }, rectRadius: 0.04 });
      s.addText(svc, { x: 0.55, y: sy + 0.02, w: 3.9, h: 0.26, fontSize: 10, color: P.white, fontFace: 'Arial' });
    });
    const eps = (br.endpoints ?? []).slice(0, 5);
    if (eps.length > 0) {
      s.addText('AFFECTED ENDPOINTS', { x: 5.0, y: 2.05, w: 4.7, h: 0.28, fontSize: 9, color: P.gray1, bold: true, charSpacing: 2, fontFace: 'Arial' });
      eps.forEach((ep, i) => {
        const ey = 2.44 + i * 0.38;
        s.addShape(pres.ShapeType.rect, { x: 5.0, y: ey, w: 4.6, h: 0.3, fill: { color: P.panel }, line: { color: P.border, width: 1 }, rectRadius: 0.04 });
        s.addText(ep, { x: 5.15, y: ey + 0.02, w: 4.3, h: 0.26, fontSize: 10, color: P.gray1, fontFace: 'Arial' });
      });
    }
    s.addText('4 / 6', { x: 9.3, y: 5.1, w: 0.6, h: 0.3, fontSize: 9, color: P.gray2, fontFace: 'Arial', align: 'right' });
  }

  // ── Slide 5: Timeline ─────────────────────────────────────────────────────
  {
    const s = pres.addSlide();
    s.background = { color: P.bg };
    s.addShape(pres.ShapeType.rect, { x: 0, y: 0, w: 10, h: 0.6, fill: { color: P.panel }, line: { color: P.border, width: 1 } });
    s.addText('EVENT TIMELINE', { x: 0.4, y: 0, w: 6, h: 0.6, fontSize: 11, bold: true, color: P.amber, fontFace: 'Arial', valign: 'middle', charSpacing: 3 });
    const typeColors: Record<string, string> = { deploy: P.orange, alert: P.red, error: P.red, recovery: P.teal, change: P.amber, info: P.blue };
    s.addShape(pres.ShapeType.line, { x: 1.42, y: 0.75, w: 0, h: 4.6, line: { color: P.border, width: 2 } });
    if (timeline.length === 0) {
      s.addText('No timeline events — run Analyze first.', { x: 1.8, y: 1.2, w: 8, h: 0.5, fontSize: 12, color: P.gray1, fontFace: 'Arial' });
    }
    timeline.forEach((ev, i) => {
      const ey = 0.75 + i * 0.65;
      const ec = typeColors[ev.type] ?? P.gray2;
      s.addShape(pres.ShapeType.ellipse, { x: 1.3, y: ey + 0.04, w: 0.24, h: 0.24, fill: { color: ec } });
      const ts = (ev.timestamp || '').replace('T', ' ').slice(0, 16);
      s.addText(ts, { x: 0, y: ey, w: 1.2, h: 0.28, fontSize: 8, color: P.gray1, fontFace: 'Arial', align: 'right' });
      s.addShape(pres.ShapeType.rect, { x: 1.72, y: ey, w: 7.9, h: 0.46, fill: { color: P.panel }, line: { color: ec, width: 1 }, rectRadius: 0.04 });
      s.addText((ev.type || 'info').toUpperCase(), { x: 1.72, y: ey, w: 0.85, h: 0.46, fontSize: 8, bold: true, color: P.white, fontFace: 'Arial', align: 'center', valign: 'middle' });
      s.addText(truncate(ev.event, 110), { x: 2.65, y: ey + 0.04, w: 6.8, h: 0.36, fontSize: 10, color: P.white, fontFace: 'Arial' });
    });
    s.addText('5 / 6', { x: 9.3, y: 5.1, w: 0.6, h: 0.3, fontSize: 9, color: P.gray2, fontFace: 'Arial', align: 'right' });
  }

  // ── Slide 6: Actions ──────────────────────────────────────────────────────
  {
    const s = pres.addSlide();
    s.background = { color: P.bg };
    s.addShape(pres.ShapeType.rect, { x: 0, y: 0, w: 10, h: 0.6, fill: { color: P.panel }, line: { color: P.border, width: 1 } });
    s.addText('RECOMMENDED ACTIONS', { x: 0.4, y: 0, w: 7, h: 0.6, fontSize: 11, bold: true, color: P.amber, fontFace: 'Arial', valign: 'middle', charSpacing: 3 });
    const actionColors = [P.red, P.orange, P.amber, P.amber, P.gray1, P.gray1];
    if (actions.length === 0) {
      s.addText('No recommended actions — run Analyze first.', { x: 0.5, y: 1.2, w: 9, h: 0.5, fontSize: 12, color: P.gray1, fontFace: 'Arial' });
    }
    actions.forEach((action, i) => {
      const ay = 0.8 + i * 0.73;
      const ac = actionColors[i] ?? P.gray1;
      s.addShape(pres.ShapeType.rect, { x: 0.35, y: ay, w: 9.3, h: 0.6, fill: { color: P.panel }, line: { color: ac, width: 1 }, rectRadius: 0.06 });
      s.addShape(pres.ShapeType.rect, { x: 0.35, y: ay, w: 0.55, h: 0.6, fill: { color: ac }, rectRadius: 0.06 });
      s.addText(String(i + 1), { x: 0.35, y: ay, w: 0.55, h: 0.6, fontSize: 14, bold: true, color: P.white, fontFace: 'Arial', align: 'center', valign: 'middle' });
      s.addText(truncate(action, 130), { x: 1.05, y: ay + 0.08, w: 8.4, h: 0.44, fontSize: 11, color: P.white, fontFace: 'Arial' });
    });
    s.addShape(pres.ShapeType.rect, { x: 0, y: 5.15, w: 10, h: 0.475, fill: { color: P.panel }, line: { color: P.border, width: 1 } });
    s.addText(`SentinelOps — Agentic Incident Commander · Generated ${genDate} · CONFIDENTIAL`, {
      x: 0.4, y: 5.2, w: 9.0, h: 0.3, fontSize: 8, color: P.gray2, fontFace: 'Arial', align: 'center',
    });
    s.addText('6 / 6', { x: 9.3, y: 5.1, w: 0.6, h: 0.3, fontSize: 9, color: P.gray2, fontFace: 'Arial', align: 'right' });
  }

  await pres.writeFile({ fileName: `${incident.id}-briefing.pptx` });
}
